# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false


## Environment Properties

mcVersion=1.21.1
mcVersionRange=[1.21,)
neoForgeVersion=21.1.248
neoForgeVersionRange=[21,)
loaderVersionRange=[4,)
parchmentMCVersion=1.21.1
parchmentMappingsVersion=2024.11.17


## Mod Properties
modId=scaredsfactions
modName=Scared's Faction Mod
modLicense=LGPL-3.0-or-later
modVersion=0.2.2.1
modGroupId=io.github.scaredsmods.scaredsfactions
modAuthors=ScaredRabbitNL
modDescription=A simple faction mod.

# Dependencies
kffVersion=5.12.0
fzzyConfigVersion=0.7.6
tabVersion=5.5.0
