#Setting this value to true will enable pvp within factions when using weapons from Superb Warfare
enableInFactionTaCZPvp = false
#Setting this value to true will enable pvp within factions when using vanilla weapons (axe and sword).
enableInFactionVanillaPvp = false
#Whether the player respawns at their faction's beacon.
respawnPlayerAtFactionBeacon = true

